pyconkr/settings-dev.py
pyconkr/settings-prod.py
pyconkr/settings.py
pyconkr/urls.py

lint: 코드 포멧 수정

---

.github/workflows/deploy_on_dev.yml

* zappa로 api 서버를 배포합니다.
* 환경변수 설정 스크립트 permission 수정

update: 환경변수 설정 스크립트 permission 수정

---

.github/workflows/pull-request-merge-precondition.yml

`black`과 더불어 일관적인 코드 스타일 유지를 위해 `isort`를 추가합니다. 
* GitHub Actions `pull-request-merge-precondition` 워크플로우에 `isort` 수행 스텝 추가

ci: Pull Request 이벤트 발생 시 `isort` 실행 절차 추가

---

.github/workflows/deploy_on_dev.yml
.github/workflows/deploy_on_prod.yml

fix: migrations은 black 검증에서 제외

---

sponsor/serializers.py

* 후원사 전체내용(상세..?)를 조회할 때, 불필요한 필드가 함께 조회됩니다.
* 저장하는 경우에도, Swagger 상에서 외부에 노출됩니다.
* 이전의 논의 결과에 따라, 국문/영문 필드를 통합합니다.
* 불필요한 필드를 삭제합니다.
* 대상 submitted
accepted
paid_at
creator
manager_id

후원사 모델 전체내용를 조회하는 경우의 불필요 필드 삭제

---

.gitignore

* don't want to commit pyc and other python related stuff by mistake 
* overwrite `.gitignore` from [github recommendation gitignore for python](https://github.com/github/gitignore/blob/main/Python.gitignore
)

following github public gitignore for python

---

sponsor/validators.py
sponsor/viewsets.py

* 잔여 구좌 갯수 검증로직을 추가합니다.
* 검증로직을 `validator`로 분리

잔여 구좌 갯수 검증로직 추가

---

pyconkr/settings.py
pyconkr/urls.py
requirements.txt

* 협업의 편리함을 위해 swagger를 추가합니다.
* drf-spectacular를 의존성에 추가합니다.
* 관련 설정을 추가합니다.
* swagger는 DEBUG=True 환경에서만 동작합니다.

swagger (drf-spectacular) 추가

---

.github/workflows/deploy_on_dev.yml
.github/workflows/deploy_on_prod.yml

* staticfile 수집 자동화
* github action 스크립트 주석 해제
* 혹시 안되면 `python manage.py "collectstatic --no-input"을 github action에서 수행하도록 수정할 예정

staticfile 수집 자동화

---

.github/workflows/deploy_on_dev.yml

* staticfile 수집 자동화 (manage.py)
* 가상환경 활성화 추가

staticfile 수집 자동화 (manage.py)

---

sponsor/models.py

* `Sponsor` 모델 `__str_` 메서드 이름을 `__str__`로 변경

`Sponsor` 모델 `__str__` 메서드 오타 수정

---

program/admin.py
program/apps.py
program/models.py
program/tests.py
program/views.py

* 프로그램 장고 앱을 추가합니다.
* 장고 앱 추가
* 모델 내용 작성

프로그램 앱 추가 및 세션/세션 유형 관련 모델 추가

---

program/models.py

* ASIS의 모호함을 해결합니다.
* 프로그램 모델 갱신

update: 모델 설계 갱신

---

program/serializers.py

* Program 앱에 Serializer 를 추가합니다.
* Program 앱에 Serializer 를 추가했습니다.
* ProposalSerializer: 각 Proposal 별 Serializer
* ProposalListSerializer: Proposal 목록 Serializer
* ProposalCategorySerializer: ProposalCategory Serializer

Add: Program 앱 Serializer 추가

---

.github/CODEOWNERS

pythonkr/PyConKR-2023
* 관리자 CODEOWNERS 를 지정합니다.
* CODEOWNERS 에 모든 파일에 대한 코드 오너에 pythonkr/PyConKR-2023 팀을 추가했습니다.

Add: CODEOWNERS 추가

---

sponsor/serializers.py
sponsor/viewsets.py

* 잔여구좌가 없는 경우, 슬롯을 닫아야 합니다.
* 잔여 구좌 조회 API에 가능여부 (`avaiable`) 필드를 추가합니다.

update: available 필드 추가

---

sponsor/serializers.py
sponsor/viewsets.py

* avaliable이 의도와 다른값을 반환합니다.
* avaliable 조건을 수정합니다.

fix: available 조건 수정

---

pyconkr/settings.py
requirements.txt

* CORS 헤더를 추가합니다.
* ALLOW ALL 활성화 (추후 수정 예정)

update: CORS-ALLOW ALL

---

pyconkr/settings.py

update: APPEND_SLASH set False

---

pyconkr/urls.py
sponsor/routers.py

update: remove trail slash

---

pyconkr/settings.py
requirements.txt
sponsor/slack.py
sponsor/viewsets.py

* 후원사 모집시 slack으로 알림을 보냅니다.
* API 호출을 위한 관련 의존성 추가
* API 호출 로직 추가

update: 후원사 슬랙 알림 추가

---

pyconkr/settings.py
requirements.txt
sponsor/slack.py
sponsor/viewsets.py

HOTFIX: 후원사 slack 알림 적용

---

sponsor/viewsets.py

slack 알림 로직 비활성화

---

sponsor/viewsets.py

* 람다 외부 인터넷 접근 확인 후 활성화
* 람다 외부 인터넷 접근 확인 후 활성화

람다 외부 인터넷 접근 확인 후 활성화

---

pyconkr/settings.py

* DRF browsable api를 비활성화 합니다.
* DRF browsable api를 비활성화 하도록 설정을 변경

Disable DRF browsable api

---

pyconkr/settings-prod.py
pyconkr/settings.py
sponsor/serializers.py

* 개발의 용이성을 위해 def browserable api 기능을 활성화 합니다.
* 겸사겸사 후원사 정보조회 api를 수정합니다.
*  browserable api 관련 설정을 `settings-prod.py`로 이동
* serializer 수정

dev에서는 browserable api 활성화 및 api 필드 수정

---

README.md
requirements-local.txt

* 로컬에서 sqlite3 기반 운용시에는 mysql 관련 의존성이 필요없으므로 제외합니다.
* 해당 의존성이 제거된 `requirements-local` 신규 생성

add: requirements-local

---

payment/admin.py
payment/apps.py
payment/models.py
payment/tests.py
payment/urls.py
payment/views.py
pyconkr/settings.py
pyconkr/urls.py

* 결제 처리를 위한 `payment` 앱을 추가합니다.
* payment app 추가

결제 처리를 위한 `payment` 앱을 추가합니다.

---

.github/workflows/pull-request-merge-precondition.yml

disble isort

---

.github/workflows/pull-request-merge-precondition.yml

disblae black

---

ticket/urls.py
ticket/views.py

* fix url matching from `re_path` to `path`
* 

fix url matching from `re_path` to `path`

---

.github/workflows/deploy_on_dev.yml
.github/workflows/deploy_on_prod.yml

disable black on deployment

---

account/urls.py
account/views.py
templates/account/login.html
templates/account/logout.html

* 아이디 페스워드 로그인을 추가합니다.
* 아이디 페스워드 로그인을 추가합니다.

feat: Add ID & PW login

---

account/urls.py

* account url path 중 오타를 수정합니다.
* account url path 중 오타를 수정합니다.

account url path 중 오타 수정

---

ticket/templates/ticket-detail.html

* 이니시스의 경우 전화번호가 필수 값 입니다.
* 티켓 구메 페이지에 전화번호 필드 추가

구매페이지 정보 수정: 전화번호 필드 추가

---

pyconkr/settings.py

* login_required view에 로그인 되지 않은 상태로 접속할 경우 리다이렉트할 로그인 페이지를 설정합니다.
* login_required view에 로그인 되지 않은 상태로 접속할 경우 리다이렉트할 로그인 페이지를 allauth가 아닌 자체 로그인 페이지 주소로 설정합니다.

login_required view에 로그인 되지 않은 상태로 접속할 경우 리다이렉트할 로그인 페이지 변경

---

account/urls.py
account/views.py

* session based login api 추가
* session based login api 추가

session based login api 추가

---

account/urls.py
account/views.py

* login api에서 모델 기반 로그인처리를 하도록 수정
* login api에서 모델 기반 로그인처리를 하도록 수정

login api에서 모델 기반 로그인처리를 하도록 수정

---

pyconkr/settings.py

* DEFAULT_AUTHENTICATION_CLASSES 수정
* DEFAULT_AUTHENTICATION_CLASSES 수정

DEFAULT_AUTHENTICATION_CLASSES 수정

---

payment/enum.py
payment/logic.py
payment/urls.py
payment/views.py

* portone callback 및 payment-key 생성 API 추가
* payment앱에 관련 코드 작성

portone callback 및 payment-key 생성 API 추가

---

payment/views.py

티켓 생성 로직 추가

---

account/logics.py
account/views.py

* 로그인 API 응답에 token 추가
* 로그인 API 응답에 token 추가

로그인 API 응답에 token 추가

---

payment/urls.py

환불 로직 URL 추가

---

payment/clients.py
pyconkr/settings.py

* constance 변수 추가
* constance 변수 추가

constance 변수 추가

---

pyconkr/settings-dev.py
requirements.txt

* mysql connector 변경
* mysql connector 변경

mysql connector 변경

---

ticket/urls.py

* ticket type api 에 slash 추가
* ticket type api 에 slash 추가

ticket type api 에 slash 추가

---

sponsor/serializers.py

* Sponsor list 조회 시 url field를 포함하여 반환
* Sponsor list 조회 시 url field를 포함하여 반환합니다.

Sponsor list 조회 시 url field를 포함하여 반환

---

pyconkr/settings.py

* 추가한 서브도메인에서 발생하는 CORS 오류를 수정합니다.
* CORS 화이트리스트에 PG 심사 임시 서브도메인 추가

CORS 화이트리스트에 PG 심사 임시 서브도메인 추가

---

payment/urls.py
payment/views.py

* payment failed api 추가
* payment failed api 추가

payment failed api 추가

---

program/models.py
program/serializers.py
program/urls.py

* 세션 상세에 사용자이름, 카테코리명 필드 추가
* 세션 상세에 사용자이름, 카테코리명 필드 추가

세션 상세에 사용자이름, 카테코리명 필드 추가

---

accounts/serializers.py
program/serializers.py

* 세션 상세에 누락된 필드 추가
* 세션 상세에 누락된 필드 추가

update: 세션 상세에 누락된 필드 추가

---

accounts/serializers.py
program/serializers.py

* 세션 목록에 누락된 필드 추가
* 세션 목록에 누락된 필드 추가

update: 세션 목록에 누락된 필드 추가

---

pyconkr/urls.py
session/urls.py

* 세션 관련 endpoint 설계 수정
* 세션 관련 endpoint 설계 수정

세션 관련 endpoint 설계 수정

---

session/admin.py
session/resources.py
session/serializers.py

* django import export
* django import export

django import export

---

program/admin.py
program/resources.py
program/serializers.py
program/urls.py
program/viewsets.py

* 스프린트, 튜토리얼 api 추가
* 스프린트, 튜토리얼 api 추가

스프린트, 튜토리얼 api 추가

---

program/resources.py

* 필드 추가: 시작/종료시각
* 필드 추가: 시작/종료시각

필드 추가: 시작/종료시각

---

sponsor/viewsets.py

후원사 정렬 기준 추가

---

sponsor/viewsets.py

* 운영 핫픽스 내용을 개발에도 반영
* 운영 핫픽스 내용을 개발에도 반영

운영 핫픽스 내용을 개발에도 반영

---

session/serializers.py
session/urls.py
session/views.py

시간표 API 추가

---

session/serializers.py

요일 정보 필드 추가

---

session/resources.py

* Migration 컬럼 추가
* Migration 컬럼 추가

Migration 컬럼 추가

---

session/serializers.py

* 누락 필드 추가 및 불필요 필드 삭제
* 누락 필드 추가 및 불필요 필드 삭제

누락 필드 추가 및 불필요 필드 삭제

---

pyconkr/settings-prod.py

운영 DB 커넥터 변경

---

program/admin.py
program/resources.py
program/serializers.py

* Program에 profile_img field를 추가하여 발표자 사진을 화면에 출력할 수 있도록 한다
* profile_img field 추가

Program에 profile_img 필드 추가

---

ticket/views.py

* response 에 아이돌봄 반영
* response 에 아이돌봄 반영

response 에 아이돌봄 반영

---

sponsor/admin.py

* 개인후원 Admin 추가
* 개인후원 Admin 추가

개인후원 Admin 추가

---

session/admin.py

세션 어드민 항목 수정

---

session/admin.py
session/serializers.py

* 세션목록 프로필 사진 필드 수정
* 세션목록 프로필 사진 필드 수정

세션목록 프로필 사진 필드 수정

---

.github/workflows/deploy_on_dev.yml
.github/workflows/deploy_on_prod.yml

* #156 번 PR에서 누락된, 현재 repo 이름을 가져오는 로직을 추가합니다.

Fix: 누락된 현재 repo 이름을 가져오는 로직 추가

---

.github/workflows/deploy_on_dev.yml
.github/workflows/deploy_on_prod.yml
.github/workflows/pull-request-merge-precondition.yml

* SyntaxError 해소 겸 EOL 대비를 위해 Python3.10으로 버전업합니다.

Feat: Python 버전업 시도

---

sponsor/serializers.py
sponsor/urls.py
sponsor/viewsets.py

* 후원사 페이지를 위한 API 구현
* 후원사 등급 별 후원사 목록 API 추가

Fix: 후원사 등급 별 후원사 목록 API 추가

---

pyconkr/settings-dev.py

* 개발용 프론트 서버에서 접근 할 수 있도록 화이트리스트 추가
* 개발용 프론트 서버에서 접근 할 수 있도록 화이트리스트 추가

Fix: 개발용 프론트 서버에서 접근 할 수 있도록 화이트리스트 추가

---

pyconkr/settings.py

* 2024 프론트 개발 페이지 cors 추가
* 2024 프론트 개발 페이지 cors 추가

Fix: 2024 프론트 개발 페이지 cors 추가

---

pyconkr/settings.py

* CORS 정보에 Schema가 누락된 버그 수정
* CORS 정보에 Schema가 누락된 버그 수정

Fix: CORS 정보에 Schema가 누락된 버그 수정

---

sponsor/viewsets.py

* 2024년 후원사 정보만 출력
* queryset에 연도 filter 추가

Fix: 해당 연도의 후원사 정보만 쿼리하도록 수정

---

sponsor/models.py
sponsor/viewsets.py

* 잘못된 queryset 빌드로 인해 api가 정상 동작 하지 않는 이슈 수정
* 잘못된 queryset 빌드로 인해 api가 정상 동작 하지 않는 이슈 수정

Fix: 잘못된 queryset 빌드로 인해 api가 정상 동작 하지 않는 이슈 수정

---

sponsor/viewsets.py

* 후원금이 입금된 후원사만 표시 되도록 수정
* 후원금이 입금된 후원사만 표시 되도록 수정

feat: 후원금이 입금된 후원사만 표시 되도록 수정

---

.github/workflows/deploy_on_dev.yml
.github/workflows/deploy_on_prod.yml
.github/workflows/pull-request-merge-precondition.yml
pyconkr/settings.py
session/viewsets.py
sponsor/viewsets.py

https://github.com/pythonkr/pyconkr-api-v2/pull/171

apply #171 

---

sponsor/admin.py

* 어드민에서 후원사 목록 조회시 500 error 현상 수정
* 

Fix: 없는 옵션을 디스플레이 하려던 버그 수정
